// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TFTools.API.Data;

#nullable disable

namespace TFTools.API.Migrations
{
    [DbContext(typeof(TFToolsDbContext))]
    partial class TFToolsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChampionTrait", b =>
                {
                    b.Property<int>("ChampionsId")
                        .HasColumnType("int");

                    b.Property<int>("TraitsId")
                        .HasColumnType("int");

                    b.HasKey("ChampionsId", "TraitsId");

                    b.HasIndex("TraitsId");

                    b.ToTable("ChampionTrait");
                });

            modelBuilder.Entity("TFTools.API.Models.Augment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TierRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Augments");
                });

            modelBuilder.Entity("TFTools.API.Models.Champion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Champions");
                });

            modelBuilder.Entity("TFTools.API.Models.ChampionAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChampionId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId")
                        .IsUnique();

                    b.ToTable("ChampionAbilities");
                });

            modelBuilder.Entity("TFTools.API.Models.ChampionRecommendedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChampionId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId");

                    b.HasIndex("ItemId");

                    b.ToTable("ChampionRecommendedItems");
                });

            modelBuilder.Entity("TFTools.API.Models.ChampionStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<double>("AttackSpeed")
                        .HasColumnType("float");

                    b.Property<int>("ChampionId")
                        .HasColumnType("int");

                    b.Property<int>("DPS1")
                        .HasColumnType("int");

                    b.Property<int>("DPS2")
                        .HasColumnType("int");

                    b.Property<int>("DPS3")
                        .HasColumnType("int");

                    b.Property<int>("Damage1")
                        .HasColumnType("int");

                    b.Property<int>("Damage2")
                        .HasColumnType("int");

                    b.Property<int>("Damage3")
                        .HasColumnType("int");

                    b.Property<int>("Health1")
                        .HasColumnType("int");

                    b.Property<int>("Health2")
                        .HasColumnType("int");

                    b.Property<int>("Health3")
                        .HasColumnType("int");

                    b.Property<int>("MR")
                        .HasColumnType("int");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<int>("StartingMana")
                        .HasColumnType("int");

                    b.Property<int>("TotalMana")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId")
                        .IsUnique();

                    b.ToTable("ChampionStats");
                });

            modelBuilder.Entity("TFTools.API.Models.Composition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarryImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConditional")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatchVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Playstyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tips")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Compositions");
                });

            modelBuilder.Entity("TFTools.API.Models.CompositionChampion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChampionId")
                        .HasColumnType("int");

                    b.Property<int>("Col")
                        .HasColumnType("int");

                    b.Property<int>("CompositionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCarry")
                        .HasColumnType("bit");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId");

                    b.HasIndex("CompositionId");

                    b.ToTable("CompositionChampions");
                });

            modelBuilder.Entity("TFTools.API.Models.CompositionChampionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompositionChampionId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompositionChampionId");

                    b.HasIndex("ItemId");

                    b.ToTable("CompositionChampionItems");
                });

            modelBuilder.Entity("TFTools.API.Models.God", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gods");
                });

            modelBuilder.Entity("TFTools.API.Models.GodOffering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GodId")
                        .HasColumnType("int");

                    b.Property<string>("Offerings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GodId");

                    b.ToTable("GodOfferings");
                });

            modelBuilder.Entity("TFTools.API.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Component1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Component2Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComponent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TierRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Component1Id");

                    b.HasIndex("Component2Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("TFTools.API.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("TFTools.API.Models.Trait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Traits");
                });

            modelBuilder.Entity("TFTools.API.Models.TraitBreakpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bonus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TraitId")
                        .HasColumnType("int");

                    b.Property<int>("UnitsRequired")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TraitId");

                    b.ToTable("TraitBreakpoints");
                });

            modelBuilder.Entity("ChampionTrait", b =>
                {
                    b.HasOne("TFTools.API.Models.Champion", null)
                        .WithMany()
                        .HasForeignKey("ChampionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TFTools.API.Models.Trait", null)
                        .WithMany()
                        .HasForeignKey("TraitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TFTools.API.Models.ChampionAbility", b =>
                {
                    b.HasOne("TFTools.API.Models.Champion", "Champion")
                        .WithOne("Ability")
                        .HasForeignKey("TFTools.API.Models.ChampionAbility", "ChampionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Champion");
                });

            modelBuilder.Entity("TFTools.API.Models.ChampionRecommendedItem", b =>
                {
                    b.HasOne("TFTools.API.Models.Champion", "Champion")
                        .WithMany("RecommendedItems")
                        .HasForeignKey("ChampionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TFTools.API.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Champion");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("TFTools.API.Models.ChampionStats", b =>
                {
                    b.HasOne("TFTools.API.Models.Champion", "Champion")
                        .WithOne("Stats")
                        .HasForeignKey("TFTools.API.Models.ChampionStats", "ChampionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Champion");
                });

            modelBuilder.Entity("TFTools.API.Models.CompositionChampion", b =>
                {
                    b.HasOne("TFTools.API.Models.Champion", "Champion")
                        .WithMany()
                        .HasForeignKey("ChampionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFTools.API.Models.Composition", "Composition")
                        .WithMany("CompositionChampions")
                        .HasForeignKey("CompositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Champion");

                    b.Navigation("Composition");
                });

            modelBuilder.Entity("TFTools.API.Models.CompositionChampionItem", b =>
                {
                    b.HasOne("TFTools.API.Models.CompositionChampion", "CompositionChampion")
                        .WithMany("Items")
                        .HasForeignKey("CompositionChampionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TFTools.API.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompositionChampion");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("TFTools.API.Models.GodOffering", b =>
                {
                    b.HasOne("TFTools.API.Models.God", "God")
                        .WithMany("Offerings")
                        .HasForeignKey("GodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("God");
                });

            modelBuilder.Entity("TFTools.API.Models.Item", b =>
                {
                    b.HasOne("TFTools.API.Models.Item", "Component1")
                        .WithMany()
                        .HasForeignKey("Component1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TFTools.API.Models.Item", "Component2")
                        .WithMany()
                        .HasForeignKey("Component2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Component1");

                    b.Navigation("Component2");
                });

            modelBuilder.Entity("TFTools.API.Models.TraitBreakpoint", b =>
                {
                    b.HasOne("TFTools.API.Models.Trait", "Trait")
                        .WithMany("Breakpoints")
                        .HasForeignKey("TraitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trait");
                });

            modelBuilder.Entity("TFTools.API.Models.Champion", b =>
                {
                    b.Navigation("Ability");

                    b.Navigation("RecommendedItems");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("TFTools.API.Models.Composition", b =>
                {
                    b.Navigation("CompositionChampions");
                });

            modelBuilder.Entity("TFTools.API.Models.CompositionChampion", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TFTools.API.Models.God", b =>
                {
                    b.Navigation("Offerings");
                });

            modelBuilder.Entity("TFTools.API.Models.Trait", b =>
                {
                    b.Navigation("Breakpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
